version: "3"
services:

  mykeycloak:
    image: jboss/keycloak:latest
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=H2
    expose:
      - "8899"
    command:
      - "-b 0.0.0.0"
      - "-Dkeycloak.import=/opt/jboss/keycloak/realm-export.json,/opt/jboss/keycloak/realm-export_epad.json"
    ports:
      - "8899:8080"
    volumes:
      - ./realm-export.json:/opt/jboss/keycloak/realm-export.json
      - ./realm-export_epad.json:/opt/jboss/keycloak/realm-export_epad.json

  mycouchdb:
    image: apache/couchdb:latest
    expose:
      - 8888
    ports:
      - "8888:5984"
    volumes:
      - ./couchdb:/opt/couchdb/data
    healthcheck:
        test: ["CMD", "bash", "-c", "curl -f http://localhost:5984/ || exit 1"]
        interval: 15s
        timeout: 15s
        retries: 15

  mydicomweb:
    image: rubinlab/dicomweb-server:latest
    expose:
     - 8090
    ports:
     - "8090:8090"
    volumes:
     - ./production_dicomweb.js:/config/development.js
    depends_on:
     - mycouchdb
     - mykeycloak

  myepadlite:
    image: rubinlab/epadlite
    expose:
     - 8080
    ports:
     - "8080:8080"
    volumes:
     - ./production_epadlite.js:/config/development.js
     - ./production_epadlite_dicomweb.json:/config/dicomweb_none.json
     - ./production_epadlite_auth.json:/config/auth.json
    depends_on:
     - mycouchdb
     - mydicomweb
     - mykeycloak

  myepadjs:
    image: rubinlab/epadjs:latest
    expose:
     - 3000
    ports:
     - "3000:3000"
    volumes:
     - ./production_epadjs.json:/app/src/config.json
     - ./production_keycloak.json:/app/public/keycloak.json
    depends_on:
     - mycouchdb
     - mydicomweb
     - mykeycloak
