version: "3"
services:
  mykeycloak:
    image: jboss/keycloak:latest
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=H2
    expose:
      - "8899"
    command:
      - "-b 0.0.0.0"
      - "-Dkeycloak.import=/opt/jboss/keycloak/realm-export.json,/opt/jboss/keycloak/realm-export_epad.json"
    ports:
      - "8899:8080"
    volumes:
      - ./realm-export.json:/opt/jboss/keycloak/realm-export.json
      - ./realm-export_epad.json:/opt/jboss/keycloak/realm-export_epad.json
    depends_on:
      - mycouchdb
  mycouchdb:
    image: apache/couchdb:latest
    expose:
      - 8888
    ports:
      - "8888:5984"
    volumes:
      - ./couchdb:/opt/couchdb/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984"]
      interval: 1m30s
      timeout: 1m
      retries: 10
  mydicomweb:
    image: rubinlab/dicomweb-server:beta 
    expose:
     - 8090
    ports:
     - "8090:8090"
    volumes:
     - ./production_dicomweb.js:/config/development.js
    depends_on:
     - mykeycloak
    healthcheck:
      test: ["CMD", "pm2", "show", "DICOMwebServer"]
      interval: 1m30s
      timeout: 1m
      retries: 10
  myepadlite:
    image: rubinlab/epadlite:beta
    expose:
     - 8080
    ports:
     - "8080:8080"
    volumes:
     - ./production_epadlite.js:/config/development.js
     - ./production_epadlite_dicomweb.json:/config/dicomweb_none.json
     - ./production_epadlite_auth.json:/config/auth.json
    depends_on:
     - myepadjs
    healthcheck:
      test: ["CMD", "pm2", "show", "ePADlite"]
      interval: 1m30s
      timeout: 1m
      retries: 10
  myepadjs:
    image: rubinlab/epadjs:beta
    expose:
     - 3000
    ports:
     - "3000:3000"
    volumes:
     - ./production_epadjs.json:/app/src/config.json
     - ./production_keycloak.json:/app/public/keycloak.json
    depends_on:
     - mydicomweb
